// Seed data + status helpers

const SERVICES = [
  {
    id: "exp",
    name: "Express Wash",
    desc: "Exterior rinse, foam wash and hand dry. In and out in 20 minutes.",
    duration: 20,
    price: 18,
    features: ["Foam wash", "Wheel rinse", "Hand dry"],
    popular: false,
  },
  {
    id: "prm",
    name: "Premium Detail",
    desc: "Full exterior + interior vacuum, dashboard wipe, and tire shine.",
    duration: 45,
    price: 38,
    features: ["Interior vacuum", "Tire shine", "Dashboard wipe", "Window clean"],
    popular: true,
  },
  {
    id: "sig",
    name: "Signature Polish",
    desc: "Premium detail plus hand wax, paint sealant, and leather conditioning.",
    duration: 90,
    price: 79,
    features: ["Hand wax", "Paint sealant", "Leather conditioning", "Engine bay wipe"],
    popular: false,
  },
  {
    id: "cer",
    name: "Ceramic Protect",
    desc: "6-month ceramic coating with paint correction. By appointment only.",
    duration: 180,
    price: 249,
    features: ["Paint correction", "6mo ceramic", "Wheel coating", "Glass coating"],
    popular: false,
  },
];

const VEHICLES = [
  {
    id: "v1",
    nickname: "Daily",
    make: "Toyota",
    model: "Camry",
    year: 2022,
    plate: "8KQR-220",
    color: "Silver",
    lastWash: "Apr 28",
  },
  {
    id: "v2",
    nickname: "Weekend",
    make: "Subaru",
    model: "Outback",
    year: 2019,
    plate: "3MTX-810",
    color: "Forest",
    lastWash: "Mar 14",
  },
];

const STATUS = {
  pending: { label: "Pending", cls: "badge-pending" },
  confirmed: { label: "Confirmed", cls: "badge-confirmed" },
  progress: { label: "In Progress", cls: "badge-progress" },
  completed: { label: "Completed", cls: "badge-completed" },
  cancelled: { label: "Cancelled", cls: "badge-cancelled" },
  noshow: { label: "No Show", cls: "badge-noshow" },
};
const PAY_STATUS = {
  pending: { label: "Pending", cls: "badge-pending" },
  confirmed: { label: "Confirmed", cls: "badge-confirmed" },
  failed: { label: "Failed", cls: "badge-failed" },
  refunded: { label: "Refunded", cls: "badge-refunded" },
};

const BOOKINGS = [
  {
    id: "BK-2841",
    customer: "Marcus Reyes",
    customerInit: "MR",
    vehicle: "Toyota Camry · 8KQR-220",
    service: "Premium Detail",
    date: "May 17",
    time: "10:30",
    status: "confirmed",
    bay: "Bay 2",
    assignee: "Diego",
    price: 38,
    pay: "confirmed",
  },
  {
    id: "BK-2840",
    customer: "Priya Shah",
    customerInit: "PS",
    vehicle: "Honda Civic · 5LWN-094",
    service: "Express Wash",
    date: "May 17",
    time: "11:15",
    status: "progress",
    bay: "Bay 1",
    assignee: "Diego",
    price: 18,
    pay: "confirmed",
  },
  {
    id: "BK-2839",
    customer: "James O'Connor",
    customerInit: "JO",
    vehicle: "Ford F-150 · 7BHR-321",
    service: "Signature Polish",
    date: "May 17",
    time: "13:00",
    status: "pending",
    bay: "—",
    assignee: "—",
    price: 79,
    pay: "pending",
  },
  {
    id: "BK-2838",
    customer: "Sora Tanaka",
    customerInit: "ST",
    vehicle: "Tesla Model 3 · TES-9911",
    service: "Premium Detail",
    date: "May 17",
    time: "14:30",
    status: "confirmed",
    bay: "Bay 3",
    assignee: "Amaya",
    price: 38,
    pay: "confirmed",
  },
  {
    id: "BK-2837",
    customer: "Leila Brooks",
    customerInit: "LB",
    vehicle: "Subaru Outback · 3MTX-810",
    service: "Ceramic Protect",
    date: "May 16",
    time: "09:00",
    status: "completed",
    bay: "Bay 2",
    assignee: "Marco",
    price: 249,
    pay: "confirmed",
  },
  {
    id: "BK-2836",
    customer: "Adam Kessler",
    customerInit: "AK",
    vehicle: "Audi Q5 · AKU-552",
    service: "Express Wash",
    date: "May 16",
    time: "16:00",
    status: "cancelled",
    bay: "—",
    assignee: "—",
    price: 18,
    pay: "refunded",
  },
  {
    id: "BK-2835",
    customer: "Hannah Lin",
    customerInit: "HL",
    vehicle: "BMW 330i · BMW-771",
    service: "Premium Detail",
    date: "May 16",
    time: "15:00",
    status: "noshow",
    bay: "—",
    assignee: "—",
    price: 38,
    pay: "failed",
  },
];

const EMPLOYEES = [
  {
    id: "e1",
    name: "Diego Marín",
    init: "DM",
    role: "Senior Detailer",
    status: "On shift",
    today: 4,
    weekly: 22,
    rating: 4.9,
    hired: "Mar 2023",
  },
  {
    id: "e2",
    name: "Amaya Khan",
    init: "AK",
    role: "Detailer",
    status: "On shift",
    today: 3,
    weekly: 18,
    rating: 4.8,
    hired: "Jun 2023",
  },
  {
    id: "e3",
    name: "Marco Silva",
    init: "MS",
    role: "Ceramic Specialist",
    status: "On shift",
    today: 1,
    weekly: 6,
    rating: 5.0,
    hired: "Oct 2022",
  },
  {
    id: "e4",
    name: "Reyna Foster",
    init: "RF",
    role: "Detailer",
    status: "Off today",
    today: 0,
    weekly: 16,
    rating: 4.7,
    hired: "Jan 2024",
  },
  {
    id: "e5",
    name: "Theo Park",
    init: "TP",
    role: "Trainee",
    status: "On shift",
    today: 2,
    weekly: 9,
    rating: 4.4,
    hired: "Feb 2026",
  },
];

const PAYMENTS = [
  { id: "PMT-1284", booking: "BK-2841", customer: "Marcus Reyes", amount: 38, method: "Card · 4242", date: "May 17", status: "confirmed" },
  { id: "PMT-1283", booking: "BK-2840", customer: "Priya Shah", amount: 18, method: "Card · 1191", date: "May 17", status: "confirmed" },
  { id: "PMT-1282", booking: "BK-2839", customer: "James O'Connor", amount: 79, method: "Pending", date: "May 17", status: "pending" },
  { id: "PMT-1281", booking: "BK-2837", customer: "Leila Brooks", amount: 249, method: "ACH transfer", date: "May 16", status: "confirmed" },
  { id: "PMT-1280", booking: "BK-2836", customer: "Adam Kessler", amount: 18, method: "Refund · 4242", date: "May 16", status: "refunded" },
  { id: "PMT-1279", booking: "BK-2835", customer: "Hannah Lin", amount: 38, method: "Card · 2014", date: "May 16", status: "failed" },
  { id: "PMT-1278", booking: "BK-2834", customer: "Theresa Park", amount: 18, method: "Card · 3009", date: "May 16", status: "confirmed" },
];

// Customer-visible bookings (subset, slightly different perspective)
const MY_BOOKINGS = [
  {
    id: "BK-2845",
    service: "Premium Detail",
    date: "May 19",
    time: "10:30",
    vehicle: "Toyota Camry",
    status: "confirmed",
    bay: "Bay 2",
    price: 38,
    pay: "confirmed",
  },
  {
    id: "BK-2812",
    service: "Express Wash",
    date: "May 02",
    time: "16:00",
    vehicle: "Toyota Camry",
    status: "completed",
    bay: "Bay 1",
    price: 18,
    pay: "confirmed",
  },
  {
    id: "BK-2799",
    service: "Signature Polish",
    date: "Apr 28",
    time: "09:30",
    vehicle: "Subaru Outback",
    status: "completed",
    bay: "Bay 3",
    price: 79,
    pay: "confirmed",
  },
  {
    id: "BK-2756",
    service: "Express Wash",
    date: "Apr 12",
    time: "14:00",
    vehicle: "Toyota Camry",
    status: "cancelled",
    bay: "—",
    price: 18,
    pay: "refunded",
  },
];

const ACTIVITY = [
  { t: "2h ago", text: "Booking BK-2840 moved to In Progress", who: "Diego" },
  { t: "Today 09:12", text: "Payment PMT-1284 captured · $38", who: "System" },
  { t: "Today 08:55", text: "BK-2841 confirmed by customer", who: "Marcus R." },
  { t: "Yesterday", text: "Ceramic Protect on Subaru Outback completed", who: "Marco" },
  { t: "Yesterday", text: "Receipt sent for BK-2837 · $249", who: "System" },
];

Object.assign(window, {
  SERVICES,
  VEHICLES,
  STATUS,
  PAY_STATUS,
  BOOKINGS,
  EMPLOYEES,
  PAYMENTS,
  MY_BOOKINGS,
  ACTIVITY,
});
